server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${blogServer.databaseName}?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: ${blogServer.username}
    password: ${blogServer.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  thymeleaf:
    cache: false
  # redis和redis session
  redis:
    port: 6379
    database: 0
    host: localhost

logging:
  level:
    root: info
    com: debug
  file:
    name: log/blog-dev.log

# jasypt加密
blogServer:
  databaseName: ENC(Lmp4gbxUltJQjVw7rCAWAGk3odvEgssF)
  username: ENC(8F9lACcnQAbBeaY33mfWK1Yu8d0Dzs6Y)
  password: ENC(2YBlechQBISr3v8Kolls3PhIghIYGmzjkSwGNvkvLjA=)