server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zmblog?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
    password: ZMMMMMMM191010
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    com: debug
  file: log/blog-dev.log
