server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.208.86:3306/zmblog?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
    password: db2022
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: true
  # redis和redis session
  redis:
    port: 6379
    database: 0
    host: 121.37.208.86
    password: redis2022

logging:
  level:
    root: warn
    com: info
  file:
    name: log/blog-pro.log